FROM golang:latest

WORKDIR /app

RUN export GO111MODULE=on

COPY * ./ 
COPY go.mod ./ 
COPY go.sum ./ 
RUN go mod download 
COPY *.go ./

#RUN go build -o main server.go

RUN cd /app && git clone https://github.com/kaeppen/disys-mock.git
RUN cd /app/disys-mock/server && go build -o main . 


CMD ["/app/disys-mock/server/main"]