// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package mock

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MockClient is the client API for Mock service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MockClient interface {
	Increment(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Value, error)
}

type mockClient struct {
	cc grpc.ClientConnInterface
}

func NewMockClient(cc grpc.ClientConnInterface) MockClient {
	return &mockClient{cc}
}

func (c *mockClient) Increment(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Value, error) {
	out := new(Value)
	err := c.cc.Invoke(ctx, "/mock.mock/Increment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MockServer is the server API for Mock service.
// All implementations must embed UnimplementedMockServer
// for forward compatibility
type MockServer interface {
	Increment(context.Context, *Request) (*Value, error)
	mustEmbedUnimplementedMockServer()
}

// UnimplementedMockServer must be embedded to have forward compatible implementations.
type UnimplementedMockServer struct {
}

func (UnimplementedMockServer) Increment(context.Context, *Request) (*Value, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Increment not implemented")
}
func (UnimplementedMockServer) mustEmbedUnimplementedMockServer() {}

// UnsafeMockServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MockServer will
// result in compilation errors.
type UnsafeMockServer interface {
	mustEmbedUnimplementedMockServer()
}

func RegisterMockServer(s grpc.ServiceRegistrar, srv MockServer) {
	s.RegisterService(&Mock_ServiceDesc, srv)
}

func _Mock_Increment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MockServer).Increment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mock.mock/Increment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MockServer).Increment(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Mock_ServiceDesc is the grpc.ServiceDesc for Mock service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Mock_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mock.mock",
	HandlerType: (*MockServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Increment",
			Handler:    _Mock_Increment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mock.proto",
}
